import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const base=process.env.REVIEW_TEST_ORIGIN||'http://localhost:5173';
if(!['localhost','127.0.0.1'].includes(new URL(base).hostname))throw new Error('Integration test only runs on a local database.');
const passcode=readFileSync('.env','utf8').split('\n').find(l=>l.startsWith('TEAM_PASSCODE='))?.slice(14);
const clients={anon:'',a:'',b:'',resume:''};let passed=0;
async function api(who,path,body,extra={}){const response=await fetch(base+path,{method:body?'POST':'GET',signal:AbortSignal.timeout(15000),headers:{...(clients[who]?{Cookie:clients[who]}:{}),...(body?{'Content-Type':'application/json',Origin:base}:{}),...extra},body:body?JSON.stringify(body):undefined});const raw=await response.text();let data;try{data=JSON.parse(raw);}catch{data={error:raw};}const cookie=response.headers.get('set-cookie');if(cookie&&response.ok)clients[who]=cookie.split(';')[0];return {status:response.status,data,cookie};}
function check(condition,label){assert.ok(condition,label);passed++;console.log('PASS '+label);}
const hash=s=>{let h=14695981039346656037n;for(let i=0;i<s.length;i++){h^=BigInt(s.charCodeAt(i));h=BigInt.asUintN(64,h*1099511628211n);}return h.toString(16);};
check((await api('anon','/api/document')).status===401,'未登录无法读取正文');
check((await api('anon','/api/review')).status===401,'未登录无法读取团队数据');
check((await api('anon','/api/review',{op:'resolve',id:'x',resolved:true})).status===401,'未登录无法写入');
check((await api('anon','/api/session',{name:'无效测试',passcode:'wrong'})).status===403,'错误口令被拒绝');
const suffix=Date.now().toString(36),nameA='验证甲-'+suffix,nameB='验证乙-'+suffix;
const a=await api('a','/api/session',{name:nameA,passcode});check(a.status===200&&a.cookie.includes('HttpOnly')&&a.cookie.includes('SameSite=Strict'),'成员甲建立受保护会话');
const b=await api('b','/api/session',{name:nameB,passcode});check(b.status===200&&b.data.person.id!==a.data.person.id,'成员乙独立署名');
check((await api('a','/api/review',{op:'resolve',id:'x',resolved:true},{Origin:'https://elsewhere.invalid'})).status===403,'跨来源写入被拒绝');
const doc=(await api('a','/api/document')).data;check(doc.features.length===122&&new Set(doc.features.map(f=>f.id)).size===122&&doc.groups.length===5,'五个业务域完整覆盖 122 项功能');
const f=doc.features[0];let state=(await api('a','/api/review')).data;
const current=id=>state.edits.find(e=>e.blockId===id)?.text??doc.blocks[id].text;
const fh=()=>hash([f.name,f.detail,f.rule].map(current).join('\u0000'));
const oldHash=fh();
check((await api('a','/api/review',{op:'review',featureId:f.id,status:'approved',note:'验证确认',contentHash:oldHash})).status===200,'甲确认功能');
check((await api('b','/api/review',{op:'review',featureId:f.id,status:'issue',note:'验证：需补充边界',contentHash:oldHash})).status===200,'乙独立提交问题');
state=(await api('a','/api/review')).data;check(state.reviews.some(r=>r.userId===a.data.person.id&&r.status==='approved')&&state.reviews.some(r=>r.userId===b.data.person.id&&r.status==='issue'),'两个成员互相可见且不覆盖');
const resume=await api('resume','/api/session',{name:nameA,passcode});check(resume.data.person.id===a.data.person.id,'同名再次进入延续原审阅');
const block=f.detail,text=current(block),version=state.edits.find(e=>e.blockId===block)?.version??0;
const anchor={blockId:block,start:0,end:Math.min(text.length,8),quote:text.slice(0,8),prefix:'',suffix:text.slice(8,48),version};
const comment=await api('b','/api/review',{op:'comment',anchors:[anchor],body:'验证划线 '+suffix});check(comment.status===200,'选中文字评论保存');
let root=comment.data.comments.find(c=>c.body==='验证划线 '+suffix);check((await api('a','/api/review')).data.comments.some(c=>c.id===root.id),'划线评论跨会话可见');
check((await api('a','/api/review',{op:'comment',parentId:root.id,body:'验证回复'})).status===200,'其他成员可回复');
check((await api('a','/api/review',{op:'comment-edit',id:root.id,body:'不能覆盖他人评论'})).status===403,'禁止修改他人署名评论');
const race=await Promise.all(['a','b'].map((who,i)=>api(who,'/api/review',{op:'edit',blockId:block,baseVersion:version,text:text+'\n验证并发 '+suffix+' '+i})));
check(race.filter(r=>r.status===200).length===1&&race.filter(r=>r.status===409).length===1,'同一版本并发修订只接受一次');
state=(await api('a','/api/review')).data;
check(state.revisions.filter(r=>r.blockId===block&&r.version===version+1).length===1,'修订历史与正文版本一致');
check(state.reviews.find(r=>r.featureId===f.id&&r.userId===a.data.person.id).contentHash!==fh(),'修订后旧确认可识别为待复核');
check((await api('a','/api/review',{op:'review',featureId:f.id,status:'approved',note:'',contentHash:oldHash})).status===409,'旧内容的确认被服务器拒绝');
check((await api('b','/api/review',{op:'comment',anchors:[anchor],body:'过期划线'})).status===409,'过期划线不会错误落位');
check((await api('a','/api/review',{op:'review',featureId:f.id,status:'approved',note:'验证复核',contentHash:fh()})).status===200,'阅读最新版本后可重新确认');
check((await api('b','/api/review',{op:'review',featureId:f.id,status:'issue',note:'',contentHash:fh()})).status===400,'问题状态要求补充说明');
const solved=await api('a','/api/review',{op:'resolve',id:root.id,resolved:true});check(solved.status===200&&solved.data.comments.find(c=>c.id===root.id).resolved,'讨论可署名标记解决');
const reopened=await api('b','/api/review',{op:'resolve',id:root.id,resolved:false});check(reopened.status===200&&!reopened.data.comments.find(c=>c.id===root.id).resolved,'讨论可以重新打开');
console.log(JSON.stringify({passed,features:doc.features.length,domains:doc.groups.map(g=>({name:g.name,count:g.count})),database:'local only'}));
