'use client';
import {useState} from 'react';
import {Check,MessageSquare,Send,Undo2,Quote,Pencil,Clock3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {effectiveStatus,featureHash,locateAnchor} from '@/lib/review-rules';
import type {Comment,Anchor} from '@/lib/types';
import {useReview,timeLabel,statusLabels,type Panel} from './context';
import {toast} from 'sonner';

function Quotes({anchors}:{anchors:Anchor[]}){const {text}=useReview();return <div className="quote-list">{anchors.map((a,i)=><blockquote key={i}><Quote size={13}/><span>{a.quote}{!locateAnchor(text(a.blockId),a)&&<small>原文已改变，此处保留当时的引用</small>}</span></blockquote>)}</div>;}

function Thread({root}:{root:Comment}){
 const {state,person,personName,mutate,busy}=useReview();const [reply,setReply]=useState(''),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState('');
 async function send(){try{await mutate({op:'comment',parentId:root.id,body:reply});setReply('');toast.success('回复已保存');}catch(e){toast.error((e as Error).message);}}
 async function edit(){try{await mutate({op:'comment-edit',id:editing,body:draft});setEditing(null);}catch(e){toast.error((e as Error).message);}}
 return <article className={`thread ${root.resolved?'thread-resolved':''}`}><div className="thread-top"><span>{root.featureId||'正文划线'} · {root.resolved?'已解决':'待讨论'}</span><Button variant="ghost" size="sm" disabled={busy} onClick={()=>{void mutate({op:'resolve',id:root.id,resolved:!root.resolved}).catch(e=>toast.error(e.message));}}>{root.resolved?<Undo2 size={13}/>:<Check size={13}/>} {root.resolved?'重新打开':'标为解决'}</Button></div><Quotes anchors={root.anchors}/>{[root,...state.comments.filter(c=>c.parentId===root.id)].map((c,i)=><div className={`comment ${i?'reply':''}`} key={c.id}><div className="comment-meta"><b>{personName(c.authorId)}</b><time>{timeLabel(c.createdAt)}</time>{c.authorId===person.id&&<button title="修改我的评论" aria-label="修改我的评论" onClick={()=>{setEditing(c.id);setDraft(c.body);}}><Pencil size={12}/></button>}</div>{editing===c.id?<div className="space-y-2"><Textarea value={draft} onChange={e=>setDraft(e.target.value)} aria-label="修改评论"/><div className="flex gap-2"><Button size="sm" disabled={busy||!draft.trim()} onClick={()=>void edit()}>保存</Button><Button size="sm" variant="ghost" onClick={()=>setEditing(null)}>取消</Button></div></div>:<p>{c.body}</p>}</div>)}{root.resolved&&<p className="resolved-by">{personName(root.resolvedBy)} 标记解决 · {timeLabel(root.updatedAt)}</p>}<div className="reply-composer"><Textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="回复这条讨论…" aria-label="回复讨论" rows={2}/><Button size="sm" disabled={busy||!reply.trim()} onClick={()=>void send()}><Send size={13}/>回复</Button></div></article>;
}

function FeatureDiscussion({id}:{id:string}){
 const {doc,state,person,text,personName,review,mutate,busy}=useReview();const f=doc.features.find(f=>f.id===id)!;const my=state.reviews.find(r=>r.featureId===id&&r.userId===person.id);const [note,setNote]=useState(my?.note??''),[message,setMessage]=useState('');
 const comments=state.comments.filter(c=>!c.parentId&&(c.featureId===id||c.anchors.some(a=>[f.name,f.detail,f.rule].includes(a.blockId))));
 async function save(status:string){try{await review(f,status,note);toast.success(status==='issue'?'问题已记录':'审阅说明已保存');}catch(e){toast.error((e as Error).message);}}
 async function discuss(){try{await mutate({op:'comment',featureId:id,body:message});setMessage('');}catch(e){toast.error((e as Error).message);}}
 return <><div className="panel-feature-title"><span className="feature-id">{id}</span><h3>{text(f.name)}</h3></div><Tabs defaultValue="review"><TabsList className="w-full"><TabsTrigger value="review" className="flex-1">逐人审阅</TabsTrigger><TabsTrigger value="discuss" className="flex-1">讨论 {comments.length}</TabsTrigger></TabsList><TabsContent value="review" className="space-y-6 pt-4"><section className="my-review"><label htmlFor="review-note">我的问题或补充说明</label><Textarea id="review-note" value={note} onChange={e=>setNote(e.target.value)} rows={5} maxLength={5000} placeholder="说明哪里需要修改、建议如何补充…"/><div className="flex flex-wrap gap-2"><Button disabled={busy||!note.trim()} onClick={()=>void save('issue')}>记录问题</Button><Button variant="outline" disabled={busy} onClick={()=>void save('approved')}><Check size={14}/>确认无误</Button><Button variant="ghost" disabled={busy||!note.trim()} onClick={()=>void save('pending')}>仅存补充</Button></div><p className="small-note">当前功能内容发生修订后，已确认或有问题的记录会提示重新复核。</p></section><section><h4 className="panel-section-title">团队审阅记录</h4>{state.reviews.filter(r=>r.featureId===id).length===0?<p className="empty-copy">还没有审阅记录，成为第一个审阅人。</p>:state.reviews.filter(r=>r.featureId===id).map(r=>{const s=effectiveStatus(r,featureHash(f,doc,state.edits));return <div className="person-review" key={r.userId}><div><b>{personName(r.userId)}</b><span className={`status-pill status-${s}`}>{statusLabels[s]}</span></div>{r.note&&<p>{r.note}</p>}<small>{timeLabel(r.updatedAt)}</small></div>;})}</section></TabsContent><TabsContent value="discuss" className="pt-4 space-y-4"><div className="new-discussion"><Textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="向团队发起讨论…" aria-label="发起功能讨论" rows={3}/><Button size="sm" disabled={busy||!message.trim()} onClick={()=>void discuss()}><MessageSquare size={13}/>发起讨论</Button></div>{comments.map(c=><Thread root={c} key={c.id}/>)}</TabsContent></Tabs></>;
}

function SelectionDiscussion({anchors}:{anchors:Anchor[]}){const {mutate,busy,setPanel}=useReview();const [body,setBody]=useState('');async function send(){try{await mutate({op:'comment',anchors,body});setBody('');setPanel({kind:'all'});toast.success('划线评论已保存，团队成员可查看和回复。');}catch(e){toast.error((e as Error).message);}}return <><Quotes anchors={anchors}/><label className="panel-section-title" htmlFor="selection-comment">你的评论</label><Textarea id="selection-comment" value={body} onChange={e=>setBody(e.target.value)} placeholder="针对选中文字提出问题或补充建议…" rows={7} maxLength={5000}/><Button disabled={busy||!body.trim()} onClick={()=>void send()}><Send size={14}/>发布划线评论</Button><p className="small-note">评论与选中文字关联。后续修订改变原文时，会保留原始引用。</p></>;}

function AllDiscussions(){const {state}=useReview();const [filter,setFilter]=useState('open');const roots=state.comments.filter(c=>!c.parentId&&(filter==='all'||c.resolved===(filter==='resolved'))).slice().reverse();return <><div className="flex items-center justify-between"><span className="small-note">{roots.length} 条讨论</span><Select value={filter} onValueChange={setFilter}><SelectTrigger className="w-[140px]" aria-label="讨论筛选"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="open">待讨论</SelectItem><SelectItem value="resolved">已解决</SelectItem><SelectItem value="all">全部讨论</SelectItem></SelectContent></Select></div>{roots.length?roots.map(c=><Thread key={c.id} root={c}/>):<div className="panel-empty"><MessageSquare size={32}/><h3>这里还没有讨论</h3><p>在正文中选中文字，或通过功能行的“问题 / 补充”开始。</p></div>}</>;}

export function DiscussionPanel({panel,onClose}:{panel:Panel;onClose:()=>void}){const {state}=useReview();const thread=panel?.kind==='thread'?state.comments.find(c=>c.id===panel.id):undefined;return <Sheet open={!!panel} onOpenChange={open=>{if(!open)onClose();}}><SheetContent className="w-full sm:max-w-[540px] gap-0"><SheetHeader className="border-b p-6"><SheetTitle>{panel?.kind==='feature'?'功能审阅':panel?.kind==='selection'?'划线评论':panel?.kind==='thread'?'讨论详情':'团队讨论'}</SheetTitle><SheetDescription>署名保存 · 所有成员共享可见</SheetDescription></SheetHeader><div className="panel-body">{panel?.kind==='feature'&&<FeatureDiscussion key={panel.id} id={panel.id}/>} {panel?.kind==='selection'&&<SelectionDiscussion key={JSON.stringify(panel.anchors)} anchors={panel.anchors}/>} {panel?.kind==='thread'&&thread&&<Thread key={thread.id} root={thread}/>} {panel?.kind==='all'&&<AllDiscussions/>}</div></SheetContent></Sheet>;}

export function RevisionLog(){const {state,personName,startEdit}=useReview();return <div className="revision-list">{!state.revisions.length?<div className="large-empty"><Clock3 size={36}/><h3>修订记录从这里开始</h3><p>点击正文或功能单元格旁的铅笔，保存后会记录作者与前后内容。</p></div>:state.revisions.map(r=><article className="revision-card" key={r.id}><header><b>{personName(r.authorId)}</b><span>{r.blockId.startsWith('M')?r.blockId.split('-').slice(0,2).join('-'):'PRD 正文'} · 第 {r.version} 次修订</span><time>{timeLabel(r.createdAt)}</time><Button variant="ghost" size="sm" onClick={()=>startEdit(r.blockId)}>查看当前内容</Button></header><div className="revision-diff"><div><small>修订前</small><p>{r.beforeText}</p></div><div><small>修订后</small><p>{r.afterText}</p></div></div></article>)}</div>;}
